id = "fossil"
name = "Fossil"
description = "Fossil language support - a data manipulation language"
version = "0.1.0"
schema_version = 1
authors = ["Ángel Iglesias Préstamo <angel.iglesias.prestamo@gmail.com>"]
repository = "https://github.com/fossil-lang/zed-fossil"

[languages.fossil]
path = "languages/fossil"

[language_servers.fossil-lsp]
name = "Fossil Language Server"
languages = ["Fossil"]

[grammars.fossil]
repository = "https://github.com/fossil-lang/tree-sitter-fossil"
commit = "d603658e249932559d167ef5d34339d20931ebf6"
